sudo: required
services:
  - docker

before_install:
  - docker build -t mkannekanti/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mkannekanti/react-rest npm test -- --coverage

after_success:
  - docker build -t mkannekanti/multi-client ./client
  - docker build -t mkannekanti/multi-nginx ./nginx
  - docker build -t mkannekanti/multi-server ./server
  - docker build -t mkannekanti/multi-worker ./worker
  # Log in to the Docker CLI
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  # - docker push mkannekanti/multi-client
  # - docker push mkannekanti/multi-nginx
  # - docker push mkannekanti/multi-server
  # - docker push mkannekanti/multi-worker

